const CONFIG={
  GOOGLE_SHEET_ID:"1-ZQQLvMGEDSwDRiigtNo2vvCZhoS3OUdgK0423gW-Jg",
  SOFTWARES_GID:"474438347",
  MIDIAS_GID:"728409259",
  SOFTWARES_CSV_URL:"https://docs.google.com/spreadsheets/d/e/2PACX-1vTkjRpZsinwht385Qhwt5-vK-Lvmf5QN88ttP07XzvX6tvNOrLwkr8NaSTHpFGfo1NiwuoR0oUP22I_/pub?gid=474438347&single=true&output=csv",
  MIDIAS_CSV_URL:"https://docs.google.com/spreadsheets/d/e/2PACX-1vTkjRpZsinwht385Qhwt5-vK-Lvmf5QN88ttP07XzvX6tvNOrLwkr8NaSTHpFGfo1NiwuoR0oUP22I_/pub?gid=728409259&single=true&output=csv",
  REFRESH_INTERVAL_MS:30000, REQUEST_TIMEOUT_MS:10000
};
const STATUS={CONSULTA:"Em Consulta",SEM_PACOTE:"Sem pacote oficial",DISPONIVEL:"Disponível no \\Mídias"};
let allRows=[],mediaRows=[],hasLoadedData=false,mediaLoaded=false;
const $=id=>document.getElementById(id);
const normalize=v=>String(v??"").replace(/^\uFEFF/,"").replace(/\u00A0/g," ").trim();
const normalizeKey=v=>normalize(v).toLowerCase().replace(/\s+/g," ");
function canonicalStatus(v){const raw=normalize(v),k=normalizeKey(raw);if(k===normalizeKey(STATUS.CONSULTA))return STATUS.CONSULTA;if(k===normalizeKey(STATUS.SEM_PACOTE))return STATUS.SEM_PACOTE;if(k===normalizeKey(STATUS.DISPONIVEL))return STATUS.DISPONIVEL;return raw;}
function isHeaderRow(a,b){return normalize(a).toLowerCase()==="software"&&normalize(b).toLowerCase()==="status";}
function setConnection(t,c="neutral"){$("connectionStatus").textContent=t;$('connectionStatus').className=`connection ${c}`;}
function showError(m,type="error"){$("errorBox").className=`notice ${type}`;$('errorBox').textContent=m;}
function hideError(){$('errorBox').className='notice hidden';}
function parseCSV(text){const rows=[];let row=[],cell="",quoted=false;for(let i=0;i<text.length;i++){const c=text[i],n=text[i+1];if(c==='"'){if(quoted&&n==='"'){cell+='"';i++;}else quoted=!quoted;}else if(c===','&&!quoted){row.push(cell);cell="";}else if((c==='\n'||c==='\r')&&!quoted){if(c==='\r'&&n==='\n')i++;row.push(cell);cell="";if(row.some(v=>normalize(v)))rows.push(row);row=[];}else cell+=c;}if(cell.length||row.length){row.push(cell);if(row.some(v=>normalize(v)))rows.push(row);}return rows;}
function mapColumns(parsed,required){if(!parsed.length)return[];const headers=parsed[0].map(normalize),low=headers.map(x=>x.toLowerCase());const indexes=required.map((name,i)=>{let idx=low.indexOf(name.toLowerCase());if(idx<0)idx=i;return idx;});return parsed.slice(1).map(r=>indexes.map(i=>normalize(r[i]))).filter(r=>r.some(Boolean));}
function parseSoftware(text){const p=parseCSV(text.replace(/^\uFEFF/,""));const rows=mapColumns(p,["Software","Status"]).map(r=>({software:r[0],status:canonicalStatus(r[1])})).filter(r=>r.software&&!isHeaderRow(r.software,r.status));return{rows,empty:!rows.length};}
function parseMedia(text){const p=parseCSV(text.replace(/^\uFEFF/,""));const rows=mapColumns(p,["Software","Tipo","Link","Observação"]).map(r=>({software:r[0],tipo:r[1],link:r[2],observacao:r[3]})).filter(r=>r.software||r.link);return{rows,empty:!rows.length};}
async function fetchText(url){const ctl=new AbortController(),timer=setTimeout(()=>ctl.abort(),CONFIG.REQUEST_TIMEOUT_MS);try{const sep=url.includes('?')?'&':'?';const res=await fetch(url+sep+'cache='+Date.now(),{cache:'no-store',mode:'cors',signal:ctl.signal});if(!res.ok)throw new Error(`HTTP ${res.status}`);return await res.text();}finally{clearTimeout(timer);}}
function fetchGoogleJsonp(gid,parser){return new Promise((resolve,reject)=>{const cb=`gs_${Date.now()}_${Math.floor(Math.random()*9999)}`,script=document.createElement('script'),timer=setTimeout(()=>cleanup(new Error('Tempo limite do Google Sheets excedido.')),CONFIG.REQUEST_TIMEOUT_MS);function cleanup(err,data){clearTimeout(timer);delete window[cb];script.remove();err?reject(err):resolve(data);}window[cb]=payload=>{try{const table=payload?.table;if(!table)throw new Error('Resposta do Google Sheets sem dados.');const cols=Array.isArray(table.cols)?table.cols:[],rows=Array.isArray(table.rows)?table.rows:[];const labels=cols.map(c=>normalize(c?.label));const vals=rows.map(row=>(Array.isArray(row?.c)?row.c:[]).map(c=>normalize(c?.v??c?.f)));const header=labels.some(Boolean)?labels:cols.map((c,i)=>normalize(c?.id)||String.fromCharCode(65+i));const csv=[header,...vals].map(r=>r.map(v=>'"'+String(v).replaceAll('"','""')+'"').join(',')).join('\n');cleanup(null,parser(csv));}catch(e){cleanup(e);}};script.onerror=()=>cleanup(new Error('O Google Sheets recusou a consulta alternativa.'));const q=encodeURIComponent(gid===CONFIG.MIDIAS_GID?'select A,B,C,D':'select A,B');const tqx=encodeURIComponent(`out:json;responseHandler:${cb}`);script.src=`https://docs.google.com/spreadsheets/d/${CONFIG.GOOGLE_SHEET_ID}/gviz/tq?gid=${gid}&tqx=${tqx}&tq=${q}`;document.head.appendChild(script);});}
async function loadSoftware(){setConnection('Consultando planilha...','loading');$('lastUpdate').textContent='Atualizando...';try{let r;try{r=parseSoftware(await fetchText(CONFIG.SOFTWARES_CSV_URL));}catch(e){r=await fetchGoogleJsonp(CONFIG.SOFTWARES_GID,parseSoftware);}allRows=r.rows;hasLoadedData=true;updateDashboard();$('lastUpdate').textContent=new Date().toLocaleString('pt-BR');setConnection('Conectado','ok');if(r.empty)showError('A aba Softwares foi acessada, mas não há softwares cadastrados.','warning');else if(mediaLoaded)hideError();}catch(e){console.error(e);setConnection('Sem conexão com a planilha','error');$('lastUpdate').textContent='Não atualizada';if(!hasLoadedData)showError('Não foi possível obter os dados da aba Softwares. Verifique a publicação do Google Sheets.','error');}}
async function loadMedia(){showMediaState('Consultando a URL CSV publicada da aba Midias...','loading');try{const r=parseMedia(await fetchText(CONFIG.MIDIAS_CSV_URL));mediaRows=r.rows;mediaLoaded=true;populateTypes();renderMedia();showMediaState(r.empty?'CSV acessível • sem registros':'CSV acessível • dados carregados',r.empty?'warning':'ok');if(r.empty)showError('A URL CSV da aba Midias foi acessada, mas não há registros. Verifique se a primeira linha contém Software | Tipo | Link | Observação e se os dados estão preenchidos.','warning');else if(hasLoadedData)hideError();}catch(e){console.error(e);mediaLoaded=false;showMediaState('Falha ao consultar o CSV da aba Midias','error');renderMediaError('Não foi possível carregar o CSV publicado da aba Midias (GID 728409259). Verifique a publicação da planilha e tente atualizar novamente.');}}
function updateDashboard(){const total=allRows.length,c=allRows.filter(r=>r.status===STATUS.CONSULTA).length,s=allRows.filter(r=>r.status===STATUS.SEM_PACOTE).length,d=allRows.filter(r=>r.status===STATUS.DISPONIVEL).length,p=total?d/total*100:0;$('total').textContent=total;$('emConsulta').textContent=c;$('semPacote').textContent=s;$('disponivel').textContent=d;$('progressPercent').textContent=`${p.toFixed(1)}%`;$('progressBar').style.width=`${p}%`;const a=total?c/total*360:0,b=total?s/total*360:0;$('donut').style.background=`conic-gradient(#d99a20 0deg ${a}deg,#d15b5b ${a}deg ${a+b}deg,#1769c2 ${a+b}deg 360deg)`;$('legend').innerHTML=`<div><span class="dot consulta-dot"></span>Em Consulta <b>${c}</b></div><div><span class="dot none-dot"></span>Sem pacote oficial <b>${s}</b></div><div><span class="dot available-dot"></span>Disponível no \\Mídias <b>${d}</b></div>`;renderSoftware();}
function statusClass(s){return s===STATUS.DISPONIVEL?'available':s===STATUS.CONSULTA?'consulta':s===STATUS.SEM_PACOTE?'none':'unknown';}
function renderSoftware(){const q=normalize($('search').value).toLowerCase(),f=normalize($('statusFilter').value),rows=allRows.filter(r=>(!q||r.software.toLowerCase().includes(q))&&(!f||r.status===f));$('resultCount').textContent=`${rows.length} registro${rows.length===1?'':'s'}`;$('softwareTable').innerHTML=rows.length?rows.map(r=>`<tr><td>${esc(r.software)}</td><td><span class="status ${statusClass(r.status)}">${esc(r.status||'Sem status')}</span></td></tr>`).join(''):`<tr><td colspan="2" class="empty">${allRows.length?'Nenhum software encontrado para os filtros atuais.':'Nenhum software cadastrado.'}</td></tr>`;}
function populateTypes(){const sel=$('mediaTypeFilter'),current=sel.value,types=[...new Set(mediaRows.map(r=>r.tipo).filter(Boolean))].sort((a,b)=>a.localeCompare(b,'pt-BR'));sel.innerHTML='<option value="">Todos os tipos</option>'+types.map(t=>`<option value="${escAttr(t)}">${esc(t)}</option>`).join('');if(types.includes(current))sel.value=current;}
function isNetworkPath(link){return /^\\\\/.test(normalize(link));}
function linkFor(link){const x=normalize(link);if(isNetworkPath(x)){const unc=x.replace(/^\\\\/,'');return 'file://'+unc.replaceAll('\\','/');}return x;}
function openMediaLink(link){const x=normalize(link);if(!x)return; if(isNetworkPath(x)){const uri=linkFor(x); try{window.location.href=uri;}catch(e){window.open(uri,'_blank');} return;} if(/^https?:\/\//i.test(x)){window.open(x,'_blank','noopener,noreferrer');return;} window.open(x,'_blank','noopener,noreferrer');}
function renderMedia(){const q=normalize($('mediaSearch').value).toLowerCase(),f=normalize($('mediaTypeFilter').value),rows=mediaRows.filter(r=>(!q||r.software.toLowerCase().includes(q))&&(!f||r.tipo===f));$('mediaResultCount').textContent=`${rows.length} registro${rows.length===1?'':'s'}`;if(!rows.length){$('mediaTable').innerHTML=`<tr><td colspan="5" class="empty">${mediaRows.length?'Nenhuma mídia encontrada para os filtros atuais.':'Nenhuma mídia cadastrada.'}</td></tr>`;return;}$('mediaTable').innerHTML=rows.map(r=>{const href=linkFor(r.link);const linkText=r.link||'—';const action=href?`<button type="button" class="open-link" onclick="openMediaLink('${escAttr(r.link).replaceAll('\'','\\\'')}')">Abrir</button>`:'—';return `<tr><td>${esc(r.software)}</td><td>${esc(r.tipo||'—')}</td><td class="link-cell" title="${escAttr(linkText)}">${esc(linkText)}</td><td>${esc(r.observacao||'—')}</td><td>${action}</td></tr>`;}).join('');}
function showMediaState(text,state){const el=$('mediaResultCount');el.textContent=text;el.className=`muted media-state ${state}`;}
function renderMediaError(m){$('mediaTable').innerHTML=`<tr><td colspan="5" class="empty">${esc(m)}</td></tr>`;$('mediaResultCount').textContent='0 registros';}
function esc(v){return String(v).replaceAll('&','&amp;').replaceAll('<','&lt;').replaceAll('>','&gt;').replaceAll('"','&quot;').replaceAll("'",'&#039;');}function escAttr(v){return esc(v);}
function showPage(page,writeHash=true){const isMedia=page==='midias';$('page-dashboard').classList.toggle('hidden-page',isMedia);$('page-midias').classList.toggle('hidden-page',!isMedia);document.querySelectorAll('.nav-btn').forEach(b=>b.classList.toggle('active',b.dataset.page===page));if(writeHash)history.pushState(null,'',`#${page}`);if(isMedia&&!mediaLoaded)loadMedia();}
function init(){
  $('search').addEventListener('input',renderSoftware);$('statusFilter').addEventListener('change',renderSoftware);$('refreshButton').addEventListener('click',loadSoftware);$('mediaButton').addEventListener('click',()=>showPage('midias'));$('mediaSearch').addEventListener('input',renderMedia);$('mediaTypeFilter').addEventListener('change',renderMedia);$('mediaRefreshButton').addEventListener('click',loadMedia);$('mediaBackButton').addEventListener('click',()=>showPage('dashboard'));document.querySelectorAll('.nav-btn').forEach(b=>b.addEventListener('click',()=>showPage(b.dataset.page)));window.addEventListener('popstate',()=>showPage(location.hash==='#midias'?'midias':'dashboard',false));showPage(location.hash==='#midias'?'midias':'dashboard',false);loadSoftware();setInterval(()=>{loadSoftware();if(mediaLoaded)loadMedia();},CONFIG.REFRESH_INTERVAL_MS);
}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',init);else init();
